#!/usr/bin/env python3
"""Writes Data/BreedData.lua from Blizzard's battle pet tables, as published by wago.tools.

Run it after a patch that adds pets, then commit the result:

    python3 tools/generate_breed_data.py            # current live (retail) build
    python3 tools/generate_breed_data.py 12.1.0.69933

The tables used (see Data/Breeds.lua for the formula):
  BattlePetBreedState    the stats of each breed (power, stamina, speed; x100)
  BattlePetSpeciesState  each species' adjustment to them
  BattlePetBreedQuality  the multiplier for each quality
"""
import csv
import io
import json
import sys
import urllib.request
from pathlib import Path

WAGO = "https://wago.tools"
OUTPUT = Path(__file__).resolve().parent.parent / "Data" / "BreedData.lua"
STAT_POWER, STAT_STAMINA, STAT_SPEED = "18", "19", "20"
# Breeds 13-22 are the female versions of 3-12, with the same stats.
BREED_IDS = range(3, 13)


def fetch(path):
    request = urllib.request.Request(WAGO + path, headers={"User-Agent": "Lineup breed data generator"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read().decode("utf-8")


def table(name, build):
    return list(csv.DictReader(io.StringIO(fetch(f"/db2/{name}/csv?build={build}"))))


def live_build():
    return json.loads(fetch("/api/builds/latest"))["wow"]["version"]


def stats(rows, key):
    """{id: [health, power, speed]} from state rows, keyed by the given column."""
    result = {}
    for row in rows:
        state = row["BattlePetStateID"]
        if state in (STAT_STAMINA, STAT_POWER, STAT_SPEED):
            values = result.setdefault(int(row[key]), [0, 0, 0])
            values[(STAT_STAMINA, STAT_POWER, STAT_SPEED).index(state)] = int(row["Value"])
    return result


def main():
    build = sys.argv[1] if len(sys.argv) > 1 else live_build()
    breeds = stats(table("BattlePetBreedState", build), "BattlePetBreedID")
    species = stats(table("BattlePetSpeciesState", build), "BattlePetSpeciesID")
    qualities = {int(row["QualityEnum"]) + 1: float(row["StateMultiplier"])
                 for row in table("BattlePetBreedQuality", build)}

    missing = [breed for breed in BREED_IDS if breed not in breeds]
    if missing or len(qualities) != 6:
        sys.exit(f"Unexpected data for build {build}: breeds missing {missing}, {len(qualities)} qualities")

    lines = [
        "local _, ns = ...",
        "",
        f"-- Generated by tools/generate_breed_data.py from Blizzard's game data (build {build}).",
        "-- Don't edit by hand; run the script again after a patch that adds pets.",
        "-- Stats are { health, power, speed }, x100 as in the game data (see Breeds.lua).",
        "ns.BreedData = {",
        f'    build = "{build}",',
        "    -- Stats of breeds 3-12 (13-22 are the same, female).",
        "    breeds = {",
    ]
    for breed in BREED_IDS:
        lines.append(f"        [{breed}] = {{ {', '.join(map(str, breeds[breed]))} }},")
    lines += ["    },", "    -- Multiplier by quality (rarity 1 = poor ... 6 = legendary).", "    qualities = {"]
    for rarity in sorted(qualities):
        lines.append(f"        [{rarity}] = {round(qualities[rarity], 4)},")
    lines += ["    },", "    -- Each species' adjustment to the breed's stats; species without one are left out.",
              "    species = {"]
    for species_id in sorted(species):
        values = species[species_id]
        if any(values):
            lines.append(f"        [{species_id}] = {{ {', '.join(map(str, values))} }},")
    lines += ["    },", "}", ""]

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(OUTPUT.parent.parent)} for build {build}: "
          f"{sum(1 for v in species.values() if any(v))} species")


if __name__ == "__main__":
    main()
